<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var \WorldnetTPS\Payment\Block\Transparent\Iframe $block
 * @see \WorldnetTPS\Payment\Block\Transparent\Iframe
 */
$code = $block->escapeHtml($block->getMethodCode());
$method = $block->getMethod();
$controller = $block->escapeHtml($block->getRequest()->getControllerName());
$orderUrl = $block->escapeUrl($this->helper('WorldnetTPS\Payment\Helper\Backend\Data')->getPlaceOrderAdminUrl());
$ccType = $block->getInfoData('cc_type');
$ccExpMonth = $block->getInfoData('cc_exp_month');
$ccExpYear = $block->getInfoData('cc_exp_year');
?>
<!-- IFRAME for request to our server -->
<iframe id="order-directpost-iframe" allowtransparency="true" frameborder="0" name="iframeSubmitOrder"
        style="display:none;width:100%;background-color:transparent"
        src="<?php print $block->escapeUrl($block->getViewFileUrl('blank.html')); ?>">
</iframe>
<!-- IFRAME for request to WorldnetTPS TPS -->
<iframe id="directpost-iframe" allowtransparency="true" frameborder="0"  name="iframeDirectPost"
        style="display:none;width:100%;background-color:transparent"
        src="<?php print $block->escapeUrl($block->getViewFileUrl('blank.html')); ?>">
</iframe>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?php /* @noEscape */ print $code; ?>"
          style="display:none;">
    <div class="admin__field _required">
        <label for="<?php /* @noEscape */ print $code; ?>_cc_type" class="admin__field-label">
            <span><?php print $block->escapeHtml(__('Credit Card Type')); ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?php /* @noEscape */ print $code; ?>_cc_type" name="payment[cc_type]"
                    class="required-entry validate-cc-type-select admin__control-select">
                <option value=""></option>
                <?php foreach ($block->getCcAvailableTypes() as $typeCode => $typeName): ?>
                    <option value="<?php print $block->escapeHtml($typeCode); ?>"
                            <?php if ($typeCode == $ccType): ?>selected="selected"<?php endif; ?>>
                        <?php print $block->escapeHtml($typeName); ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="admin__field _required">
        <label for="<?php /* @noEscape */ print $code; ?>_cc_number" class="admin__field-label">
            <span><?php print $block->escapeHtml(__('Credit Card Number')); ?></span>
        </label>

        <div class="admin__field-control">
            <input type="text" id="<?php /* @noEscape */ print $code; ?>_cc_number"
                   name="payment[cc_number]"
                   class="input-text required-entry validate-cc-number admin__control-text"
                   value="<?php /* @noEscape */ print $block->getInfoData('cc_number'); ?>"/>
        </div>
    </div>
    <div class="admin__field _required">
        <label for="<?php /* @noEscape */ print $code; ?>_expiration" class="admin__field-label">
            <span><?php print $block->escapeHtml(__('Expiration Date')); ?></span>
        </label>

        <div class="admin__field-control">
            <select id="<?php /* @noEscape */ print $code; ?>_expiration"
                    name="payment[cc_exp_month]"
                    class="validate-cc-exp required-entry admin__control-select admin__control-select-month">
                <?php foreach ($block->getCcMonths() as $k => $v): ?>
                    <option value="<?php print $block->escapeHtml($k); ?>"
                            <?php if ($k == $ccExpMonth): ?>selected="selected"<?php endif; ?>>
                        <?php print $block->escapeHtml($v); ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <select id="<?php /* @noEscape */ print $code; ?>_expiration_yr"
                    name="payment[cc_exp_year]"
                    class="required-entry admin__control-select admin__control-select-year">
                <?php foreach ($block->getCcYears() as $k => $v): ?>
                    <option value="<?php /* @noEscape */ print $k ? $block->escapeHtml($k) : ''; ?>"
                            <?php if ($k == $ccExpYear): ?>selected="selected"<?php endif; ?>>
                        <?php print $block->escapeHtml($v); ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="admin__field _required">
        <label for="<?php /* @noEscape */ print $code; ?>_cc_cid">
            <span><?php print $block->escapeHtml(__('Card Verification Number')); ?></span>
        </label>

        <div class="admin__field-control">
            <input type="text"
                   class="required-entry input-text validate-cc-cvn admin__control-text"
                   id="<?php /* @noEscape */ print $code; ?>_cc_cid" name="payment[cc_cid]"
                   value="<?php /* @noEscape */ print $block->getInfoData('cc_cid') ?>"/>
        </div>
    </div>
</fieldset>
<script>
    require([
        'prototype',
        'Magento_Sales/order/create/scripts',
        "Magento_Sales/order/create/form",
        'WorldnetTPS_Payment/js/direct-post'
    ], function(){

        /**
         * Disable card server validation in admin
         */
        order.addExcludedPaymentMethod('<?php /* @noEscape */ print $code; ?>');

        <?php if (!$block->isAjaxRequest()): ?>
            document.observe('dom:loaded', function(){
        <?php endif; ?>

        directPostModel = new directPost(
            '<?php /* @noEscape */ print $code; ?>',
            'directpost-iframe',
            '<?php /* @noEscape */ print $controller; ?>',
            '<?php /* @noEscape */ print $orderUrl; ?>',
            '<?php print $block->escapeUrl($method->getCgiUrl()); ?>',
            '<?php print $block->escapeUrl($block->getUrl('*/*/save', [
                '_secure' => $block->getRequest()->isSecure()
            ]));?>');

        <?php if (!$block->isAjaxRequest()): ?>
            });
        <?php endif; ?>
    });
</script>
